### ISSUE TITLE
 Not putting any export sounds not preventing any import

### ISSUE THREAD

**Issue by ouaibsky** [adamw/veripacks#5]
Hi

I have a basic use case which is:
By default each subpackage of a package must be protected (no way to use class across different package)

I did this basic test (java, not scala):

``` java
foo.intf {
 class A() {
   .... new B();
   ..... new C();
}

foo.impl {
class B () {
     .... new A();
..... new C();
}

foo.util {
class C() {
new A();
new B();
}
```

Then I call 

``` java
VeripacksBuilder$.MODULE$
                .build()
                .verify("foo")
                .throwIfNotOk();
```

And I got no errors, which sounds not in line with documentation
I tried to define a packahe-info into "foo"

``` java
@ExportSubpackages("util")
```

Again no errors

The only option I found to stop using class between package is to put in each sub-package a package-info with 

``` java
@RequiresImport
```

Do I Missed something ?
Thx in advance
Christophe

**Comment by adamw** [comment]
If you want to automatically require importing of packages, I think you should use `VeripacksBuilder.requireImportOf("foo")`. This will apply to all sub-packages as well. Also see "Requiring import for 3rd party libraries" in the readme - maybe the title of section is wrong there in fact :) Let me know if this helps

**Comment by ouaibsky** [comment]
Thx for the answer

I didn't get the point that we have many methods in MODULE.
The precedence is also important

I success by doing something like that and putting a couple of @ExportAll...

```
        VeripacksBuilder$.MODULE$
                .doNotRequireImportOf("foo.util").requireImportOf("foo")
                .build()
                .verify("foo")
                .throwIfNotOk();
```

**Comment by adamw** [comment]
great, so anything to fix in this issue or can I close? :)

**Comment by ouaibsky** [comment]
Yep you can close
Thx again
